### ISSUE TITLE
Any way you could reconsider the yellow bottom bar?

### ISSUE THREAD

**Issue by loganintech** [dylantmarsh/monokai-vibrant#1]
It's a bit... harsh on the eyes. Particularly at night.

**Comment by dylantmarsh** [comment]
Absolutely, I want to release a few versions so you can control the bottom bar color (including just black). Thanks for suggesting, it just confirms something I wanted to update.

**Comment by loganintech** [comment]
@dylantmarsh 

No problem. I'd also like to see (or help?) with full sidebar theme support. I was using Monokai Pro but it really bugs me the creator wants to charge for a theme. I get wanting to be paid for your work but if the base program is open source and whatever extension / theme you make doesn't take as long to make as the base program, you shouldn't charge for it.

My two cents anyways.

**Comment by Roeefl** [comment]
I would also love another color option for the bottom bar :)

**Comment by dylantmarsh** [comment]
The yellow bar was replaced in 0.5.0 with a dark one. Additional color options may come down the road if this theme continues to get traction. I am certainly open to contributions via pull request. Thanks for the feedback~
