### ISSUE TITLE
Is it possible to get syntax highlighting in doc comments?

### ISSUE THREAD

**Issue by jkelleyrtp** [dylantmarsh/monokai-vibrant#10]
Lots of other themes seem to support this - this particular theme is the only one I have installed that doesn't. I imagine it's as simple as modifying the token colors to include comments?

**Comment by dylantmarsh** [comment]
@jkelleyrtp Can you provide me with some examples of what you would like highlighted within a doc comment? I will work on it if VS Code has scopes for it. Thanks!

**Comment by dylantmarsh** [comment]
The latest release improves the syntax highlighting within JSDoc. Hopefully, that helps!

![code](https://user-images.githubusercontent.com/10099657/187103269-55e98582-b271-4805-83c2-8d98b53466c5.png)
