### ISSUE TITLE
Is there JS/TS semantic highlighting support?

### ISSUE THREAD

**Issue by ItamarShDev** [dylantmarsh/monokai-vibrant#13]

**Comment by dylantmarsh** [comment]
I just released 0.5.3 to the marketplace, which enables semantic highlighting. 42e4b624a6c130866907fdd9213d74b32a0d3cc1

**Comment by ItamarShDev** [comment]
This has never changes, let and const for example look the same


![Screenshot 2023-05-07 at 9 57 14](https://user-images.githubusercontent.com/953371/236662705-b03de02d-3ef0-4e90-bf1f-941cd33e81dd.png)
