### ISSUE TITLE
Font missing?

### ISSUE THREAD

**Issue by Vortilion** [dylantmarsh/monokai-vibrant#15]
I just installed your theme, it seems theres a font missing, the italic, handwritten one.

**Comment by dylantmarsh** [comment]
A font is not included with the theme. You can optionally decide to use something like [Operator Mono](https://www.typography.com/fonts/operator/overview) or [Dank Mono](https://philpl.gumroad.com/l/dank-mono). If you are looking for a free monospaced programming font with ligatures (doesn't include cursive italicized keywords), you should look at [Fira Code](https://github.com/tonsky/FiraCode).
