### ISSUE TITLE
Version without italicized operators?

### ISSUE THREAD

**Issue by Danovich** [dylantmarsh/monokai-vibrant#2]
Love the font but I'm using font ligatures and the italicized operators not working with ligatures.
Is it possible to have a version with no italicized operators?
![noLiga](https://user-images.githubusercontent.com/26672793/62409478-d86f8600-b5e0-11e9-8c6f-d7f54c1bc581.jpg)
![noLiga2](https://user-images.githubusercontent.com/26672793/62409556-f5f11f80-b5e1-11e9-92c1-ae3ff529b169.jpg)

**Comment by dylantmarsh** [comment]
@Danovich The italicized operators do not actually break the ligatures with monokai-vibrant. You just need to enable them again when you switch to the theme. Go to Settings -> Text Editor -> Font and check the box Font Ligatures. Just tested with Fira Code and it works great.

<img width="473" alt="Screen Shot 2019-08-05 at 9 00 10 AM" src="https://user-images.githubusercontent.com/10099657/62466586-a5073580-b75f-11e9-8451-e975da592ee4.png">

Closing for now but feel free to respond if you are still having trouble.
