### ISSUE TITLE
Make the pipes straight?

### ISSUE THREAD

**Issue by JacobZwang** [dylantmarsh/monokai-vibrant#4]
I love this theme, I can't use anything else now but the fact the pipes look like slashes makes coding in languages like Rust and Haskell very difficult. Could you change this or direct me to where I can change it for myself?
![image](https://user-images.githubusercontent.com/59858341/101874959-a6f4bc00-3b3e-11eb-85b4-319505bdafe3.png)

**Comment by jkelleyrtp** [comment]
Fixed my pipes with this settings override:

```json
  "editor.tokenColorCustomizations": {
    "[Monokai Vibrant]": {
      "textMateRules": [
        {
          "scope": [
            "keyword",
            "keyword.operator",
            "keyword.operator.logical",
            "keyword.operator.constructor"
          ],
          "settings": {
            "foreground": "#FF3F4F",
            "fontStyle": "bold"
          }
        }
      ]
    }
  }
```

https://stackoverflow.com/a/57426933/8167854

**Comment by JacobZwang** [comment]
> Fixed my pipes with this settings override:
> 
> ```json
>   "editor.tokenColorCustomizations": {
>     "[Monokai Vibrant]": {
>       "textMateRules": [
>         {
>           "scope": [
>             "keyword",
>             "keyword.operator",
>             "keyword.operator.logical",
>             "keyword.operator.constructor"
>           ],
>           "settings": {
>             "foreground": "#FF3F4F",
>             "fontStyle": "bold"
>           }
>         }
>       ]
>     }
>   }
> ```
> 
> https://stackoverflow.com/a/57426933/8167854

Thanks!
