### ISSUE TITLE
Syntax highlighting issue

### ISSUE THREAD

**Issue by okridgway** [dylantmarsh/monokai-vibrant#9]
While I'm not super clear on where things are going awry, at least in `C` triply nested structs don't have the correct highlighting.
![Screen Shot 2022-02-16 at 5 01 49 PM](https://user-images.githubusercontent.com/19399895/154372440-99259fb3-8e8f-404e-b805-03902da06caa.png)

**Comment by raymoff** [comment]
Hey @okridgway!  Could you please attach this piece of code or similar one? I will have a look at this issue and try to find a solution.

**Comment by dylantmarsh** [comment]
I spent some time looking into this. The issue I am running into is that there is no `variable.other.object` scope on this. The other `foo` keywords all have this textmate scope except when inside of the first if in a case. I will close this for now as I cannot see any way to fix it.

<img width="506" alt="Screen Shot 2022-08-28 at 7 30 29 PM" src="https://user-images.githubusercontent.com/10099657/187099179-9b67140a-dc83-4017-ad7e-ffaec4a43a85.png">
